"""One-shot setup for a repository.

    sanity init

Creates `.sanity/` with a starter config and warn-mode custom rules, installs
agent hooks that cancel sloppy tool calls, compiles instruction files, and
writes a `.pre-commit-config.yaml` pinned to the published sanity repo.
Nothing is overwritten unless `--force` is passed.
"""

import os
import shutil

STARTERS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "starters")

# Pin to the public repo so `pre-commit install` actually installs sanity —
# `language: system` only works if the user already pip-installed the CLI.
PRE_COMMIT_ENTRY = """\
  - repo: https://github.com/fearlessfara/sanity
    rev: v0.4.1
    hooks:
      - id: sanity-comments
      - id: sanity-rules
      # Optional AI judge (commit-msg). Needs judge.enabled=true and
      # judge.provider=api plus an API key.
      # - id: sanity-judge
"""

PRE_COMMIT_HEADER = """\
# Generated by `sanity init`. Pin `rev` to a release tag:
# https://github.com/fearlessfara/sanity/releases
repos:
"""


def seed_config(root, force=False):
    directory = os.path.join(root, ".sanity")
    os.makedirs(directory, exist_ok=True)
    target = os.path.join(directory, "config.json")
    if os.path.exists(target) and not force:
        return target, False
    shutil.copyfile(os.path.join(STARTERS, "config.json"), target)
    return target, True


def seed_rules(root, force=False):
    """Copy starter rule files that are not already present."""
    source_dir = os.path.join(STARTERS, "rules")
    target_dir = os.path.join(root, ".sanity", "rules")
    os.makedirs(target_dir, exist_ok=True)
    written, kept = [], []
    for name in sorted(os.listdir(source_dir)):
        if not name.endswith(".md"):
            continue
        target = os.path.join(target_dir, name)
        if os.path.exists(target) and not force:
            kept.append(target)
            continue
        shutil.copyfile(os.path.join(source_dir, name), target)
        written.append(target)
    return written, kept


def ensure_pre_commit(root, force=False):
    """Write or merge sanity hooks into `.pre-commit-config.yaml`."""
    path = os.path.join(root, ".pre-commit-config.yaml")
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(PRE_COMMIT_HEADER + PRE_COMMIT_ENTRY)
        return path, "wrote"

    with open(path, encoding="utf-8") as handle:
        existing = handle.read()
    if "fearlessfara/sanity" in existing or "id: sanity-comments" in existing:
        return path, "unchanged"

    with open(path, "a", encoding="utf-8") as handle:
        if not existing.endswith("\n"):
            handle.write("\n")
        handle.write("\n# --- sanity (added by sanity init) ---\n")
        handle.write(PRE_COMMIT_ENTRY)
    return path, "merged"
