"""One-shot setup for a repository.

    sanity init

Creates `.sanity/` with a starter config and warn-mode rules, installs agent
hooks, compiles instruction files, and writes a `.pre-commit-config.yaml`
snippet (or merges into an existing one). Nothing is overwritten unless
`--force` is passed — existing rules and hand-written CLAUDE.md content stay.
"""

import os
import shutil

STARTERS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "starters")

PRE_COMMIT_ENTRY = """\
  - repo: local
    hooks:
      - id: sanity-comments
        name: sanity — comments that restate the code
        entry: sanity comments
        language: system
        types: [text]
      - id: sanity-rules
        name: sanity — repository rules
        entry: sanity rules
        language: system
        types: [text]
      - id: sanity-judge
        name: sanity — AI judge (opt-in via .sanity/config.json)
        entry: sanity judge --commit
        language: system
        stages: [commit-msg]
"""

PRE_COMMIT_HEADER = """\
# Generated by `sanity init`. Prefer pinning the published repo:
#   repo: https://github.com/fearlessfara/sanity
#   rev: v0.4.0
# `language: system` below assumes `sanity` is on PATH (pip install).
repos:
"""


def seed_config(root, force=False):
    directory = os.path.join(root, ".sanity")
    os.makedirs(directory, exist_ok=True)
    target = os.path.join(directory, "config.json")
    if os.path.exists(target) and not force:
        return target, False
    shutil.copyfile(os.path.join(STARTERS, "config.json"), target)
    return target, True


def seed_rules(root, force=False):
    """Copy starter rule files that are not already present."""
    source_dir = os.path.join(STARTERS, "rules")
    target_dir = os.path.join(root, ".sanity", "rules")
    os.makedirs(target_dir, exist_ok=True)
    written, kept = [], []
    for name in sorted(os.listdir(source_dir)):
        if not name.endswith(".md"):
            continue
        target = os.path.join(target_dir, name)
        if os.path.exists(target) and not force:
            kept.append(target)
            continue
        shutil.copyfile(os.path.join(source_dir, name), target)
        written.append(target)
    return written, kept


def ensure_pre_commit(root, force=False):
    """Write or merge a local sanity entry into `.pre-commit-config.yaml`."""
    path = os.path.join(root, ".pre-commit-config.yaml")
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(PRE_COMMIT_HEADER + PRE_COMMIT_ENTRY)
        return path, "wrote"

    with open(path, encoding="utf-8") as handle:
        existing = handle.read()
    if "sanity comments" in existing or "id: sanity-comments" in existing:
        return path, "unchanged"

    with open(path, "a", encoding="utf-8") as handle:
        if not existing.endswith("\n"):
            handle.write("\n")
        handle.write("\n# --- sanity (added by sanity init) ---\n")
        handle.write(PRE_COMMIT_ENTRY)
    return path, "merged"
