"""One-shot setup for a repository.

    sanity init

Creates `.sanity/` with a starter config and a natural-language starter rule,
installs agent stop hooks, compiles instruction files, and writes a
`.pre-commit-config.yaml` pinned to the published sanity repo.
"""

import os
import shutil

STARTERS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "starters")

PRE_COMMIT_ENTRY = """\
  - repo: https://github.com/fearlessfara/sanity
    rev: v0.6.0
    hooks:
      - id: sanity-judge-rules
      # Optional: does the commit message match the staged diff?
      # Needs judge.enabled=true as well.
      # - id: sanity-judge
"""

PRE_COMMIT_HEADER = """\
# Generated by `sanity init`. Pin `rev` to a release tag:
# https://github.com/fearlessfara/sanity/releases
repos:
"""

GITIGNORE_ENTRY = "# sanity judge cache (local only, safe to delete)\n.sanity/cache/\n"


def seed_config(root, force=False):
    directory = os.path.join(root, ".sanity")
    os.makedirs(directory, exist_ok=True)
    target = os.path.join(directory, "config.json")
    if os.path.exists(target) and not force:
        return target, False
    shutil.copyfile(os.path.join(STARTERS, "config.json"), target)
    return target, True


def seed_rules(root, force=False):
    source_dir = os.path.join(STARTERS, "rules")
    target_dir = os.path.join(root, ".sanity", "rules")
    os.makedirs(target_dir, exist_ok=True)
    written, kept = [], []
    for name in sorted(os.listdir(source_dir)):
        if not name.endswith(".md"):
            continue
        target = os.path.join(target_dir, name)
        if os.path.exists(target) and not force:
            kept.append(target)
            continue
        shutil.copyfile(os.path.join(source_dir, name), target)
        written.append(target)
    return written, kept


def ensure_pre_commit(root, force=False):
    path = os.path.join(root, ".pre-commit-config.yaml")
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(PRE_COMMIT_HEADER + PRE_COMMIT_ENTRY)
        return path, "wrote"

    with open(path, encoding="utf-8") as handle:
        existing = handle.read()
    if "fearlessfara/sanity" in existing or "id: sanity-judge-rules" in existing:
        return path, "unchanged"

    with open(path, "a", encoding="utf-8") as handle:
        if not existing.endswith("\n"):
            handle.write("\n")
        handle.write("\n# --- sanity (added by sanity init) ---\n")
        handle.write(PRE_COMMIT_ENTRY)
    return path, "merged"


def ensure_gitignore(root):
    """`.sanity/cache/` holds judge verdicts, keyed by diff content — local
    scratch, not something to commit. Idempotent, unlike the rest of init."""
    path = os.path.join(root, ".gitignore")
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(GITIGNORE_ENTRY)
        return path, "wrote"

    with open(path, encoding="utf-8") as handle:
        existing = handle.read()
    if ".sanity/cache" in existing:
        return path, "unchanged"

    with open(path, "a", encoding="utf-8") as handle:
        if existing and not existing.endswith("\n"):
            handle.write("\n")
        handle.write("\n" + GITIGNORE_ENTRY)
    return path, "appended"
